"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-04-19 20:24:01.716401
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blackout_dates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('products', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('call_to_action_url', sa.String(length=500), nullable=True),
    sa.Column('tone', sa.Enum('PROFESSIONAL', 'CASUAL', 'FUN', name='tone'), nullable=False),
    sa.Column('length', sa.Enum('SHORT', 'MEDIUM', 'LONG', name='length'), nullable=False),
    sa.Column('emoji_density', sa.Enum('NONE', 'LIGHT', 'MEDIUM', 'HEAVY', name='emojidensity'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('post_type_ratios', sa.JSON(), nullable=False),
    sa.Column('posting_window_start_hour', sa.Integer(), nullable=False),
    sa.Column('posting_window_end_hour', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('posts_per_day', sa.Integer(), nullable=False),
    sa.Column('review_before_posting', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_types', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='planstatus'), nullable=False),
    sa.Column('generation_params', sa.JSON(), nullable=False),
    sa.Column('chat_history', sa.JSON(), nullable=False),
    sa.Column('generation_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('humanizer_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('typing_wpm_min', sa.Integer(), nullable=False),
    sa.Column('typing_wpm_max', sa.Integer(), nullable=False),
    sa.Column('mistake_rate', sa.Float(), nullable=False),
    sa.Column('pause_between_sentences_ms_min', sa.Integer(), nullable=False),
    sa.Column('pause_between_sentences_ms_max', sa.Integer(), nullable=False),
    sa.Column('mouse_path_curvature', sa.Float(), nullable=False),
    sa.Column('idle_scroll_before_post_sec_min', sa.Integer(), nullable=False),
    sa.Column('idle_scroll_before_post_sec_max', sa.Integer(), nullable=False),
    sa.Column('schedule_jitter_minutes', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures_threshold', sa.Integer(), nullable=False),
    sa.Column('smart_pause_minutes', sa.Integer(), nullable=False),
    sa.Column('smart_pause_until', sa.DateTime(), nullable=True),
    sa.Column('smart_pause_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.Enum('IMAGE', 'VIDEO', name='mediakind'), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('local_path', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('ai_caption', sa.Text(), nullable=True),
    sa.Column('ai_tags', sa.JSON(), nullable=False),
    sa.Column('tags_user', sa.JSON(), nullable=False),
    sa.Column('variants_json', sa.JSON(), nullable=False),
    sa.Column('tagged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_id', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_credentials_platform_id'), ['platform_id'], unique=False)

    op.create_table('session_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'WARNING', 'CHECKPOINT', 'SHADOW_BAN_SUSPECTED', 'PAUSED', name='sessionhealthstatus'), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_reason', sa.Text(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id')
    )
    op.create_table('targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_id', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('list_name', sa.String(length=100), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('description_snippet', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='targetreviewstatus'), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimizer_proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('current_value', sa.JSON(), nullable=False),
    sa.Column('proposed_value', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPLIED', 'REJECTED', name='proposalstatus'), nullable=False),
    sa.Column('auto_applied', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['analyst_reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_type', sa.Enum('INFORMATIVE', 'SOFT_SELL', 'HARD_SELL', 'ENGAGEMENT', 'STORY', 'MOTIVATIONAL', 'TESTIMONIAL', 'HOT_TAKE', 'SEASONAL', name='posttype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'SCHEDULED', 'POSTING', 'POSTED', 'FAILED', 'SKIPPED', name='poststatus'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('media_asset_id', sa.Integer(), nullable=True),
    sa.Column('first_comment', sa.Text(), nullable=True),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('generation_model', sa.String(length=100), nullable=True),
    sa.Column('generation_cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Enum('UP', 'DOWN', name='feedbackrating'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_post_id'), ['post_id'], unique=False)

    op.create_table('few_shot_examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.Enum('INFORMATIVE', 'SOFT_SELL', 'HARD_SELL', 'ENGAGEMENT', 'STORY', 'MOTIVATIONAL', 'TESTIMONIAL', 'HOT_TAKE', 'SEASONAL', name='posttype'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('few_shot_examples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_few_shot_examples_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_few_shot_examples_post_type'), ['post_type'], unique=False)

    op.create_table('plan_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('post_type', sa.Enum('INFORMATIVE', 'SOFT_SELL', 'HARD_SELL', 'ENGAGEMENT', 'STORY', 'MOTIVATIONAL', 'TESTIMONIAL', 'HOT_TAKE', 'SEASONAL', name='posttype'), nullable=False),
    sa.Column('topic_hint', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'GENERATED', 'SCHEDULED', 'POSTED', 'SKIPPED', name='slotstatus'), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('media_asset_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['content_plans.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_variants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'SCHEDULED', 'POSTING', 'POSTED', 'FAILED', 'SKIPPED', name='poststatus'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('external_post_id', sa.String(length=500), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_variants_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_variants_target_id'), ['target_id'], unique=False)

    op.create_table('post_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('window', sa.Enum('ONE_HOUR', 'ONE_DAY', 'SEVEN_DAY', name='metricswindow'), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['post_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_metrics_variant_id'), ['variant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_metrics_variant_id'))

    op.drop_table('post_metrics')
    with op.batch_alter_table('post_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_variants_target_id'))
        batch_op.drop_index(batch_op.f('ix_post_variants_post_id'))

    op.drop_table('post_variants')
    op.drop_table('plan_slots')
    with op.batch_alter_table('few_shot_examples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_few_shot_examples_post_type'))
        batch_op.drop_index(batch_op.f('ix_few_shot_examples_post_id'))

    op.drop_table('few_shot_examples')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_post_id'))

    op.drop_table('feedback')
    op.drop_table('posts')
    op.drop_table('optimizer_proposals')
    op.drop_table('targets')
    op.drop_table('session_health')
    with op.batch_alter_table('platform_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_credentials_platform_id'))

    op.drop_table('platform_credentials')
    op.drop_table('media_assets')
    op.drop_table('logs')
    op.drop_table('humanizer_profiles')
    op.drop_table('content_plans')
    op.drop_table('business_profile')
    op.drop_table('blackout_dates')
    op.drop_table('analyst_reports')
    # ### end Alembic commands ###
